"""added_url

Revision ID: 97a28c9f7342
Revises: 40fd35974f65
Create Date: 2022-06-15 20:00:29.762768

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97a28c9f7342'
down_revision = '40fd35974f65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings_vk_groups', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('settings_vk_groups', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings_vk_groups', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_column('settings_vk_groups', 'url')
    # ### end Alembic commands ###
